### ISSUE TITLE
Thirst Commands

### ISSUE THREAD

**Issue by nihal111** [Terasology/Thirst#3]
-  The `thirstCheck` command should have a DEBUG_PERMISSION
-  The `thirstrSet` and `thirstSetMax` command should have a CHEAT_PERMISSION

Look at https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/logic/console/commands/CoreCommands.java for usage references.

**Comment by TheFlash98** [comment]
Couldn't find anything command related on that link, may be you meant https://github.com/Terasology/Hunger/blob/master/src/main/java/org/terasology/hunger/HungerClientSystem.java ? 😄

**Comment by xrtariq2594** [comment]
Erm @nihal111 and @TheFlash98, these three commands already exist in [ThirstClientSystem.java](https://github.com/Terasology/Thirst/blob/master/src/main/java/org/terasology/thirst/ThirstClientSystem.java). 

They do need their permissions properly setup though.

**Comment by nihal111** [comment]
@xrtariq2594 Oh, my bad. My local repository was out of date.

**Comment by Cervator** [comment]
Closing this as complete :-)

(sorry for getting some streams crossed - I didn't notice this called for specific permissions and figured all three should be cheat)
